# Generated by Django 6.1.1 on 2026-09-22 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_order_orderitem_digitalcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={"ordering": ("price", "id")},
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="store.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="digitalcode",
            index=models.Index(
                fields=["product", "variant", "is_used"],
                name="store_digit_product_e3ca8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="digitalcode",
            index=models.Index(
                fields=["order_item"], name="store_digit_order_i_004fcf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="store_order_user_id_f28375_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-created_at"], name="store_order_status_7b2658_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="store_order_order_i_70b6d9_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["product"], name="store_order_product_056298_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="store_produ_created_0fbdf8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="store_produ_categor_6683b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "is_active"], name="store_produ_product_cd7aec_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="discount",
            constraint=models.CheckConstraint(
                condition=models.Q(("percent__gte", 0), ("percent__lte", 100)),
                name="discount_percent_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="discount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("starts_at__isnull", True),
                    ("ends_at__isnull", True),
                    ("starts_at__lte", models.F("ends_at")),
                    _connector="OR",
                ),
                name="discount_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("payment_ref", ""), _negated=True),
                fields=("payment_ref",),
                name="unique_non_empty_payment_ref",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="order_item_quantity_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)),
                fields=("product",),
                name="one_main_image_per_product",
            ),
        ),
    ]
