# Generated by Django 6.1.1 on 2026-09-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_category_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="digitalcode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_used", False),
                        ("order_item__isnull", True),
                        ("used_at__isnull", True),
                    ),
                    models.Q(
                        ("is_used", True),
                        ("order_item__isnull", False),
                        ("used_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="digitalcode_usage_state_consistent",
            ),
        ),
    ]
