# Generated by Django 6.1.1 on 2026-09-26 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_digitalcode_digitalcode_usage_state_consistent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway", models.CharField(default="zarinpal", max_length=40)),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="IRR", max_length=10)),
                (
                    "authority",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                ("reference_id", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "ایجاد شد"),
                            ("redirected", "ارسال به درگاه"),
                            ("verifying", "در حال تأیید"),
                            ("paid", "پرداخت موفق"),
                            ("failed", "ناموفق"),
                            ("canceled", "لغو شده"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("gateway_code", models.CharField(blank=True, max_length=30)),
                ("gateway_message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="store.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="store_payme_status_fd7120_idx",
                    ),
                    models.Index(
                        fields=["gateway", "authority"],
                        name="store_payme_gateway_774517_idx",
                    ),
                ],
            },
        ),
    ]
