# Generated by Django 6.1.1 on 2026-09-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bestseller_priority",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="عدد کمتر = نمایش زودتر در بخش پرفروش\u200cها.",
                verbose_name="اولویت پرفروش",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_bestseller",
            field=models.BooleanField(
                default=False,
                help_text="نمایش محصول در بخش پرفروش\u200cهای صفحه اصلی.",
                verbose_name="پرفروش",
            ),
        ),
    ]
