# Generated by Django 5.2.17 on 2026-09-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_coupon_couponredemption_loyaltyaccount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitalcode",
            name="code",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
